In [3]:
import numpy as np #Creating alias np for numpy

In [4]:
#Numpy is for numerical calculation
#It stores data in grid(Arrays)
np.array([1,2,4,5,76,7,3]) #1 D array
#Same list indexing and slicing techniqe

array([ 1,  2,  4,  5, 76,  7,  3])

In [14]:
x = np.array([[1,2,3,4],[1,12,3,4],[1,2,3,4],[34,543,65,56]])

In [15]:
x

array([[  1,   2,   3,   4],
       [  1,  12,   3,   4],
       [  1,   2,   3,   4],
       [ 34, 543,  65,  56]])

In [18]:
x[1,1] #Single value of row and col
#x[row,col]

12

In [20]:
x[1:3,1:3]
x[:3,1:3] #No need to mention start
x[:3,1:] #no need to mention the end

array([[ 2,  3,  4],
       [12,  3,  4],
       [ 2,  3,  4]])

In [21]:
x.shape

(4, 4)

In [23]:
x

array([[  1,   2,   3,   4],
       [  1,  12,   3,   4],
       [  1,   2,   3,   4],
       [ 34, 543,  65,  56]])

In [24]:
x.T #Transpose of matrix

array([[  1,   1,   1,  34],
       [  2,  12,   2, 543],
       [  3,   3,   3,  65],
       [  4,   4,   4,  56]])

In [25]:
x = np.array([[10,20,30],[40,50,60],[10,30,50]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [10, 30, 50]])

In [31]:
y = np.array([[1,2,3],[2,50,4],[5,6,7]])
y

array([[ 1,  2,  3],
       [ 2, 50,  4],
       [ 5,  6,  7]])

In [32]:
x + y #Adding every element of one 2D array to 2D array

array([[ 11,  22,  33],
       [ 42, 100,  64],
       [ 15,  36,  57]])

In [33]:
x - y

array([[ 9, 18, 27],
       [38,  0, 56],
       [ 5, 24, 43]])

In [34]:
 x == y

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [35]:
print(x * y) #Element wise multiplication

array([[  10,   40,   90],
       [  80, 2500,  240],
       [  50,  180,  350]])

In [36]:
x / y #element wise division

array([[10.        , 10.        , 10.        ],
       [20.        ,  1.        , 15.        ],
       [ 2.        ,  5.        ,  7.14285714]])

In [42]:
np.zeros((4,3))#Tuple as argument(row,col)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones((4,3))#Tuple as argument(row,col)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [46]:
np.eye(3) #Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.random((3,3))

array([[0.51346   , 0.06033082, 0.75150215],
       [0.12873142, 0.91138986, 0.86418526],
       [0.75276734, 0.45175274, 0.70384326]])

In [50]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [10, 30, 50]])

In [55]:
np.empty_like(x)

array([[4602800056068645661, 4588855408968414848, 4604944149175176941],
       [4593806058419639472, 4606384289636939141, 4605959108353302974],
       [4604955544955140729, 4601809673719607144, 4604514876028662651]])

In [ ]:
#Indexing


In [56]:
x = np.array([[10,20,30],[40,50,60],[10,30,50]])
x

array([[10, 20, 30],
       [40, 50, 60],
       [10, 30, 50]])

In [57]:
x[[0,2,1],[1,2,0]] #View from same array #

array([20, 50, 40])

In [59]:
np.array([x[0,1],x[2,2],x[1,0]]) #Seperate array

array([20, 50, 40])

In [60]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [10, 30, 50]])

In [64]:
x > 5 #Creates a array of true false


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [65]:
x[x > 5] #creates a array of all element greater than 5

array([10, 20, 30, 40, 50, 60, 10, 30, 50])

In [69]:
np.add(x,y) #x + y
np.subtract(x,y) #x-y
np.multiply(x,y) #x*y
np.divide(x,y) #x /y
np.sqrt(x)
np.mod()

<ufunc 'remainder'>

In [70]:
np.dot(x,y) #dot product


array([[ 200, 1200,  320],
       [ 440, 2940,  740],
       [ 320, 1820,  500]])

In [72]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [10, 30, 50]])

In [73]:
np.sum(x,axis=1)

array([ 60, 150,  90])

In [74]:
np.sum(x,axis=0)

array([ 60, 100, 140])

In [75]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [10, 30, 50]])

In [78]:
x=x[:2,:]

In [79]:
x

array([[10, 20, 30],
       [40, 50, 60]])

In [80]:
np.reshape(x,(3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [85]:
x = np.array([[1,2],[3,4]],dtype=np.int64)

In [87]:
np.ones((3,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])